name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/cli@v1
        with:
          inlineScript: |
            RESOURCE_GROUP=appsvc_linux_centralus
            CONTAINER_APPS_ENV=managedEnvironment-appsvclinuxcent-988a
            CONTAINER_APP_NAME=mlyoutube
            IMAGE=elitang/youtube:latest
            LOCATION='"East US"'

            if ! az group show --name $RESOURCE_GROUP > /dev/null 2>&1; then
              echo "Resource group does not exist. Creating..."
              az group create --name $RESOURCE_GROUP --location $LOCATION
            fi

            if ! az containerapp env show --name $CONTAINER_APPS_ENV --resource-group $RESOURCE_GROUP > /dev/null 2>&1; then
              echo "Container Apps environment does not exist. Creating..."
              az containerapp env create --name $CONTAINER_APPS_ENV --resource-group $RESOURCE_GROUP --location $LOCATION
            fi

            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $IMAGE \
              --environment-name $CONTAINER_APPS_ENV